version: '3.8'

services:
  api:
    build:
      context: ../
      dockerfile: ./deploy/Dockerfile.local
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - ../:/usr/src/
    ports:
      - 8080:8080
    env_file:
      - ./.env.local
    depends_on:
      - pg
      - migration
  pg:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./.env.local
  migration:
    build:
      context: ../
      dockerfile: ./deploy/Dockerfile.local
    env_file:
      - ./.env.local
    command: >
      sh -c "python manage.py flush --noinput &&
             python manage.py migrate &&
             python manage.py createsuperuser --noinput --username admin --email admin@task.test"
    volumes:
      - ../:/usr/src/
    depends_on:
      - pg

volumes:
  postgres_data: