FROM python:3.10-slim-bookworm

WORKDIR /usr/src

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
RUN pip install --upgrade pip
COPY ./deploy/requirements.txt .
RUN pip install -r requirements.txt
RUN apt-get update && \
    apt-get install -y libpq-dev

# copy project
COPY backend .
COPY manage.py .
